POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsc3RlcDA3IiwiaWQiOiI2MDljMjE5ZGIzMDY0Njc2MTQ3MmQ5YzAiLCJpYXQiOjE2MjA4OTA5NzV9.bLH_j1fVXuhS5jGLsDNTzWqzfqE9qPrkN8dvhIvL3Rk

{
    "content": "Authorized note without user id",
    "important": true
}
